image: debian/stable
packages:
  - lua5.3
  - lua5.3-dev
  - pkg-config
  - xxd
  - make
sources:
  - https://git.sr.ht/~shakna/suckgen
  - https://git.sr.ht/~shakna/shatterealm
tasks:
  - build: |
     cd suckgen
     make
  - deploy: |
     cd shatterealm
     ../suckgen/suckgen
