image: debian/stable
packages:
  - lua5.3
  - lua5.3-dev
  - pkg-config
  - xxd
  - make
  - curl
  - zip
  - valgrind
  - python3
  - python3-requests
secrets:
  - b1896a8e-ceb4-4d5b-abf2-6e6016f47212
sources:
  - https://git.sr.ht/~shakna/suckgen
  - https://git.sr.ht/~shakna/shatterealm
tasks:
  - build: |
     cd suckgen
     make all
     make test SUPPRESS='--suppressions=debian_suppress'
  - generate_blog: |
     cd shatterealm
     ../suckgen/suckgen
  - deploy_blog: |
     cd shatterealm
     sh deploy_netlify.sh
