image: debian/stable
packages:
  - lua5.3
  - lua5.3-dev
  - pkg-config
  - xxd
  - make
  - curl
  - zip
secrets:
  - 7d143ee9-613a-499b-b28e-bc871e180ecf
sources:
  - https://git.sr.ht/~shakna/suckgen
  - https://git.sr.ht/~shakna/shatterealm
tasks:
  - build: |
     cd suckgen
     make
  - generate_blog: |
     cd shatterealm
     ../suckgen/suckgen
  - deploy_blog: |
     cd shatterealm
     sh deploy_netlify.sh
